[package]
name = "stupid_encoder"
version = "0.1.0"
authors = ["Neowutran <me@neowutran.ovh>"]

[dependencies]
serde = "1.0" # if you're using `derive(Deserialize)`
serde_derive = "1.0" # if you're using `derive(Deserialize)`
docopt = "1"
